; ===== Extension 101 =====

[101]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=101-auth
aors=101

[101-auth]
type=auth
auth_type=userpass
username=101
password=123456

[101]
type=aor
max_contacts=1

; ===== Extension 102 =====

[102]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=102-auth
aors=102

[102-auth]
type=auth
auth_type=userpass
username=102
password=123456

[102]
type=aor
max_contacts=1
